# Generated by Django 3.0.7 on 2022-01-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('user_email', models.CharField(max_length=30)),
                ('user_desc', models.CharField(max_length=500)),
                ('user_phone', models.CharField(max_length=30)),
                ('user_birthday', models.DateField()),
            ],
        ),
    ]
