# Generated by Django 4.0 on 2023-06-13 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('user_email', models.CharField(max_length=30)),
                ('user_desc', models.CharField(max_length=500)),
                ('user_phone', models.CharField(max_length=30)),
                ('user_birthday', models.DateField()),
                ('user_pic', models.FileField(blank=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='userFollowers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='user.userdata')),
                ('following', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='following', to='user.userdata')),
            ],
        ),
    ]
