# Generated by Django 4.1.7 on 2023-03-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="userData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=30)),
                ("user_email", models.CharField(max_length=30)),
                ("user_desc", models.CharField(max_length=500)),
                ("user_phone", models.CharField(max_length=30)),
                ("user_birthday", models.DateField()),
                ("user_pic", models.ImageField(blank=True, upload_to="images")),
            ],
        ),
    ]
