# Generated by Django 3.0.7 on 2022-01-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='user_pic',
            field=models.ImageField(blank=True, upload_to='user/user_pics'),
        ),
    ]
